sudo: required
language: node_js
node_js:
  - 10
before_script: npm update
script:
  - npm run dist-$TRAVIS_OS_NAME
os:
  - windows
  - linux
  - osx
addons:
  apt:
    packages:
    - python
    - libsecret-1-0
    - libsecret-1-dev
    - libgnome-keyring-dev
python:
  - "2.7"
before_deploy:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export version=$(cat package.json | grep
  '"version"' | cut -d '"' -f4); if [[ "$TRAVIS_TAG" == *"-"* ]]; then export deb_distribution=unstable;
  else export deb_distribution=stable; fi; if [[ "$TRAVIS_BRANCH" == "master" ]];
  then export deb_distribution=nightly; fi; export date=$(date +%Y-%m-%d); cp packaging/debian/bintray.json
  bintray.json; sed -i s/'{version}'/$version/g bintray.json; sed -i s/'{date}'/$date/g
  bintray.json; sed -i s/'{deb_distribution}'/$deb_distribution/g bintray.json; make deb; fi;
deploy:
- provider: releases
  api_key:
    secure: WXsFv62P7BYeM0s32rcGx/LqdwECQRvUJWJ8YDZ4jdv8w4O4vlCLURiwW/65WNi7peKiMpPmv7q/NOtNrXT1PDIMyeMeJvToHGELyepGex0v1goqfURExpIEm8ddC2HiJf7ctgk7V5CichL/1DpJ2BWzCMUi1OnhLfjWpXQz4OZN8X5XwcgtMjUzEy/Ry1xMbbhrBs4a3IKyBJsbN7TRWibHsJHfl5pvk5qq7xL2s8/5/vEwMDZYFdK8BraF9AOUSqTqrDv2dfdkQrbZNiS2vPGAHdP+YRGGlbZoyHU10wIYJ3zEJ5zVtnAxa7TawZaomPVo6eglr9EuE5D79LVQVHLpBiSfAUViYuZkgxaAgeh4lpgpHgjeIYbetZ4arAcpov3Dnkpqc2Iu95M2jN5ehFtSP23OBoSxseJ3aHwQEnKJy9N6Yhww+l6E6HGqUaa+cVlVdP2zhu462oWH/4HVb1V9yrXij5+/Lo/JWYw58t86gpQTL3DmQQ0SSSj/iwaTN/qpJtzRv2ZfTY7RDS/MUiCZLf8zJ4c+BzBUVBRhIvq8LGusVhszOUhkHqndtaGHGI0+anNvvCTLUv09tOhp1m7uLB6xRloxQPdIcYfNN20+WL/zUYqOLmUx3wc0bpLh8LCHj8wbGYW7RbYcKQw66BmKgfLxUdBEBISDkgKuYx0=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
- provider: bintray
  file: bintray.json
  user: raffis
  skip_cleanup: true
  key:
    secure: "Viph5bQg16WFN7db/xt/e3BaUwhxYt6q5jtUeZOBYSCGclmBjYUH2faGayZLsoeEy7ZauVC8eekgQ8uytyyWj9289jL6tRXWpM6XzVkXvr1TwBf0khhn9R6uwzslNVtAwfk4/RhielB0WkII56FF/NrC2KY1mpysHUszDymjG1C0ipS1qKmJqqvEUifeQ1cq/CPXuy7TRIvsn3Qnpde00uUudwlHsYqB50VyJviMMTr2QbxkcODSGrCu53Y0rlUs0DlroEgC3P7E2u8neG+tIP7FXlDSWrRXOt1RzEbckOG9GkJkQAmo2BxXrPxeFMxGBhJA2rUgBc9Fn/EBAxQ1TVJK4cDtOQzEkB17an8jGikQSWQNfUo5XUI/h3Ynv0hSgUeoc/+r2S7/JZTOnjQXSEU6KkJeUJ6UnHVqsvQ/AjMc/IGxh5bS+ZDZQrpGZfja+whZAeTd1uecvWLm75R8kLTMW6dEPcGQyIyv72Y21SOtadCdaHygckyeA8sLBGkrf3/BIBQf2FGaMv0cZJQv5Kf9dwKX6Qjp0KP6nvJ/wKngr+hcM+y6oER/iygP75MUpVLAi8vh1W+gql23n5c6kQENrg2KsJ5jrd6zsnn3V6xCr6dY+OxLa/gt1DI9EDnfJAOjciJDWE4FaNvOiuLYB6DyiWGMPMLep1FKEIi3mj8="
  on:
    condition: $TRAVIS_OS_NAME = "linux"
    tags: true
