environment:
  matrix:
    - nodejs_version: '8'
version: "{build}"
build: off
matrix:
  fast_finish: true
install:
  - ps: $env:channel = "unstable"
  - ps: Install-Product node $env:nodejs_version x64
  - npm set progress=false
  - npm prune
  - npm install
  - npm run build
  - npm run dist-windows
test_script:
  - node --version
  - npm --version
  - SET PATH=C:\Program Files\Nodejs;%PATH%
artifacts: 
  - path: dist\tubectl-win-x64.exe
    name: tubectl
deploy:
  provider: GitHub
  auth_token:
    secure: jCxEiL6iLQGMyFkFptVvRACVSMy4HC9RzzLPzl1FCQsj9JNZObW+vnhYuP0tnfPy
  artifact: tubectl
  draft: false
  force_update: true
  on:
    appveyor_repo_tag: true
