environment:
  matrix:
    - nodejs_version: '8'

version: "{build}"
build: off
matrix:
  fast_finish: true

install:
  - ps: $env:channel = "unstable"
  - ps: Install-Product node $env:nodejs_version x64
  - npm set progress=false
  - npm prune
  - npm install
  - npm run build
  - npm run dist-win

test_script:
  - node --version
  - npm --version
  - SET PATH=C:\Program Files\Nodejs;%PATH%
